#端口号配置
server:
  port: 8089 #数据库连接配置
spring:
  profiles:
    active:
      common
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sal-management-system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true& serverTimezone=UTC
    username: root
    password: 123456
jwt:
  secret: com.scau
  expiration: 3000000
